spring.application.name=portfolio-backend

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Define in "appliction-local.properties" or in "docker-compose.yml"
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/portfolio_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:your_username}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_password}
#

spring.jpa.hibernate.ddl-auto=update

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Define in "appliction-local.properties" or in "docker-compose.yml"
app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:5173}

#Email service configuration
spring.mail.host=${SPRING_EMAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_EMAIL_PORT:587}

#Define in "appliction-local.properties" or in "docker-compose.yml
spring.mail.username=${SPRING_EMAIL_USERNAME:tuoindirizzo@example.com}
spring.mail.password=${SPRING_EMAIL_PASSWORD:PASSWORD_APP}
#

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true